# Generated by Django 2.2.1 on 2019-09-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField()),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('tipo', models.CharField(max_length=20)),
                ('pagamento', models.CharField(max_length=20)),
                ('vendedor', models.CharField(max_length=150)),
                ('observacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Itens_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'S')], max_length=14)),
                ('descricao', models.CharField(max_length=150)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido')),
            ],
        ),
    ]
