# Generated by Django 2.2.6 on 2019-10-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens_pedido',
            name='tipo',
        ),
    ]
