# Generated by Django 2.2.1 on 2019-10-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens_pedido',
            name='tipo',
        ),
    ]
