# Generated by Django 2.2.2 on 2019-08-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField()),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('tipo', models.CharField(max_length=20)),
                ('pagamento', models.CharField(max_length=20)),
                ('vendedor', models.CharField(max_length=150)),
                ('observacao', models.CharField(max_length=200)),
            ],
        ),
    ]
