# Generated by Django 2.2.1 on 2019-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itens_pedido_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(max_length=14)),
                ('animal', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('banho', models.BooleanField(default=False)),
                ('tosa', models.BooleanField(default=False)),
                ('vacina', models.BooleanField(default=False)),
                ('taxi', models.BooleanField(default=False)),
                ('observacao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
