# Generated by Django 2.2.1 on 2019-05-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190523_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='status',
        ),
    ]
