# Generated by Django 2.2.1 on 2019-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='animal',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='proprietario',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='telefone',
            field=models.CharField(max_length=60),
        ),
    ]
