# Generated by Django 2.2.1 on 2019-09-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itens_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id_produto',
        ),
    ]
