# Generated by Django 2.2.1 on 2019-10-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='efetivado',
            field=models.BooleanField(default=False),
        ),
    ]
