# Generated by Django 2.2.1 on 2019-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_produto_id_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_bar',
            field=models.CharField(max_length=200),
        ),
    ]
