# Generated by Django 2.2.1 on 2019-09-29 19:45

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190929_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamentos',
            name='banho',
        ),
        migrations.RemoveField(
            model_name='agendamentos',
            name='taxi',
        ),
        migrations.RemoveField(
            model_name='agendamentos',
            name='tosa',
        ),
        migrations.RemoveField(
            model_name='agendamentos',
            name='vacina',
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='servico',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 29, 19, 45, 39, 221518, tzinfo=utc)),
        ),
    ]
