# Generated by Django 2.2.1 on 2019-09-29 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190929_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
