# Generated by Django 2.2.1 on 2019-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField()),
                ('cliente_nome', models.CharField(max_length=200)),
                ('produto_id', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=150)),
            ],
        ),
    ]
