# Generated by Django 2.2.1 on 2019-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='produto_id',
            field=models.IntegerField(default=0),
        ),
    ]
