# Generated by Django 2.2.1 on 2019-09-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190929_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
