# Generated by Django 2.2.1 on 2019-09-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190929_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servicos'),
        ),
    ]
