# Generated by Django 2.2.1 on 2019-10-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191027_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='core.Produto'),
        ),
    ]
