# Generated by Django 2.2.1 on 2019-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190929_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='serv_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
