# Generated by Django 2.2.1 on 2019-10-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191027_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
