# Generated by Django 2.2.1 on 2019-10-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191027_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens_pedido',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
