# Generated by Django 2.2.1 on 2019-11-03 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191029_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.IntegerField()),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='emissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(default='Dinheiro', max_length=60),
            preserve_default=False,
        ),
    ]
