# Generated by Django 2.2.1 on 2019-11-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191103_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
