# Generated by Django 2.2.1 on 2019-11-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedido_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos_pagamento',
            name='condicao',
        ),
    ]
