# Generated by Django 2.2.1 on 2019-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191103_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saida',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='saida',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='user_name',
        ),
        migrations.AddField(
            model_name='saida',
            name='produto_descricao',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
