# Generated by Django 2.2.1 on 2019-11-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191103_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='core.Produto'),
        ),
    ]
