# Generated by Django 2.2.1 on 2019-11-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191103_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='Pedido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pedido_saida', to='core.Pedido'),
            preserve_default=False,
        ),
    ]
