# Generated by Django 2.2.1 on 2019-11-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_saida_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='fornecedor_id',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='user_name',
        ),
        migrations.AddField(
            model_name='entrada',
            name='Pedido',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_entrada', to='core.Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornece',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_entrada', to='core.Fornecedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='produto',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='produto_entrada', to='core.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='produto_descricao',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
