# Generated by Django 2.2.4 on 2019-11-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191103_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='venda',
        ),
    ]
