# Generated by Django 2.2.4 on 2019-11-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191110_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='dia',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='core.Servicos'),
        ),
    ]
