# Generated by Django 2.2.4 on 2019-12-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191130_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='dia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='hora',
            field=models.CharField(max_length=10),
        ),
    ]
