# Generated by Django 2.2.4 on 2019-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191205_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_tel',
            field=models.TextField(),
        ),
    ]
